### ISSUE TITLE
M10 Support

### ISSUE THREAD

**Issue by vargablood** [JacKeTUs/simagic-ff#1]
i would love to use it with my simagic M10, should it work adding the production/vendor id ? 

*edit* i can confirm its working out of the box using the classic m10 base.

**Comment by vargablood** [comment]
ive checked mine and theyre equal to the alphas... will try it today :)

**Comment by JacKeTUs** [comment]
Yeah, it should work, I'll add it, thank you!

**Comment by JacKeTUs** [comment]
Added more info to the README.md with this pull: https://github.com/JacKeTUs/simagic-ff/pull/2
